"""ネイティブが日常会話で使う重要単語のプリセット集"""

PRESET_CATEGORIES = {
    "日常会話 基本": [
        {"english": "actually", "japanese": "実は、実際に", "example": "Actually, I changed my mind."},
        {"english": "pretty", "japanese": "かなり、けっこう", "example": "It's pretty cold today."},
        {"english": "stuff", "japanese": "もの、こと", "example": "I have a lot of stuff to do."},
        {"english": "figure out", "japanese": "理解する、解決する", "example": "I'll figure it out later."},
        {"english": "hang out", "japanese": "遊ぶ、ぶらぶらする", "example": "Let's hang out this weekend."},
        {"english": "grab", "japanese": "さっと取る、買う", "example": "Let's grab some coffee."},
        {"english": "kind of", "japanese": "ちょっと、なんとなく", "example": "I'm kind of tired."},
        {"english": "guess", "japanese": "〜だと思う、推測する", "example": "I guess you're right."},
        {"english": "mean", "japanese": "意味する、意地悪な", "example": "What do you mean?"},
        {"english": "matter", "japanese": "重要である、問題", "example": "It doesn't matter."},
        {"english": "bother", "japanese": "悩ませる、面倒をかける", "example": "Sorry to bother you."},
        {"english": "worth", "japanese": "〜の価値がある", "example": "It's worth trying."},
        {"english": "used to", "japanese": "以前は〜だった", "example": "I used to live in Tokyo."},
        {"english": "get rid of", "japanese": "〜を取り除く、捨てる", "example": "I need to get rid of these old clothes."},
        {"english": "look forward to", "japanese": "〜を楽しみにする", "example": "I'm looking forward to the trip."},
    ],
    "日常会話 リアクション": [
        {"english": "absolutely", "japanese": "もちろん、絶対に", "example": "Absolutely! I'd love to come."},
        {"english": "definitely", "japanese": "間違いなく、ぜひ", "example": "I'll definitely be there."},
        {"english": "exactly", "japanese": "その通り、まさに", "example": "That's exactly what I meant."},
        {"english": "seriously", "japanese": "マジで、本気で", "example": "Are you seriously going to do that?"},
        {"english": "no way", "japanese": "まさか、ありえない", "example": "No way! That's amazing!"},
        {"english": "apparently", "japanese": "どうやら〜らしい", "example": "Apparently, he quit his job."},
        {"english": "literally", "japanese": "文字通り、本当に", "example": "I literally can't believe it."},
        {"english": "obviously", "japanese": "明らかに、もちろん", "example": "Obviously, that's not going to work."},
        {"english": "hopefully", "japanese": "うまくいけば", "example": "Hopefully, it won't rain tomorrow."},
        {"english": "honestly", "japanese": "正直に言うと", "example": "Honestly, I don't really care."},
        {"english": "by the way", "japanese": "ところで", "example": "By the way, did you hear the news?"},
        {"english": "never mind", "japanese": "気にしないで", "example": "Never mind, I found it."},
    ],
    "感情・気持ち": [
        {"english": "annoyed", "japanese": "イライラした", "example": "I'm so annoyed by the noise."},
        {"english": "exhausted", "japanese": "疲れ果てた", "example": "I'm exhausted after the long day."},
        {"english": "relieved", "japanese": "安心した、ほっとした", "example": "I'm relieved to hear that."},
        {"english": "embarrassed", "japanese": "恥ずかしい", "example": "I was so embarrassed."},
        {"english": "frustrated", "japanese": "イライラする、もどかしい", "example": "I'm frustrated with this situation."},
        {"english": "confused", "japanese": "混乱した、困惑した", "example": "I'm confused about what to do."},
        {"english": "impressed", "japanese": "感心した、感動した", "example": "I'm really impressed by your work."},
        {"english": "awkward", "japanese": "気まずい、ぎこちない", "example": "That was an awkward silence."},
        {"english": "overwhelmed", "japanese": "圧倒された、手に負えない", "example": "I feel overwhelmed with all this work."},
        {"english": "grateful", "japanese": "感謝している", "example": "I'm grateful for your help."},
        {"english": "upset", "japanese": "動揺した、怒った", "example": "She was upset about the news."},
        {"english": "thrilled", "japanese": "ワクワクした、大喜びの", "example": "I'm thrilled to meet you!"},
    ],
    "仕事・ビジネス": [
        {"english": "deadline", "japanese": "締め切り", "example": "The deadline is next Friday."},
        {"english": "schedule", "japanese": "予定、スケジュール", "example": "Let me check my schedule."},
        {"english": "available", "japanese": "利用可能な、空いている", "example": "Are you available tomorrow?"},
        {"english": "confirm", "japanese": "確認する", "example": "Can you confirm the meeting time?"},
        {"english": "regarding", "japanese": "〜に関して", "example": "I'm calling regarding the order."},
        {"english": "in charge of", "japanese": "〜を担当している", "example": "Who's in charge of this project?"},
        {"english": "come up with", "japanese": "〜を思いつく", "example": "We need to come up with a new idea."},
        {"english": "keep track of", "japanese": "〜を把握する、記録する", "example": "I need to keep track of my expenses."},
        {"english": "turn out", "japanese": "結局〜になる", "example": "It turned out to be a great idea."},
        {"english": "put off", "japanese": "延期する", "example": "Let's not put off the decision."},
        {"english": "catch up", "japanese": "追いつく、近況を話す", "example": "Let's catch up over lunch."},
        {"english": "follow up", "japanese": "フォローアップする", "example": "I'll follow up with an email."},
    ],
    "買い物・レストラン": [
        {"english": "checkout", "japanese": "会計、レジ", "example": "The checkout line is long."},
        {"english": "receipt", "japanese": "レシート、領収書", "example": "Can I have a receipt, please?"},
        {"english": "discount", "japanese": "割引", "example": "Is there a student discount?"},
        {"english": "refund", "japanese": "返金", "example": "I'd like to get a refund."},
        {"english": "reservation", "japanese": "予約", "example": "I have a reservation for two."},
        {"english": "recommend", "japanese": "おすすめする", "example": "What do you recommend?"},
        {"english": "appetizer", "japanese": "前菜", "example": "Should we order an appetizer?"},
        {"english": "bill", "japanese": "請求書、勘定", "example": "Can I have the bill, please?"},
        {"english": "tip", "japanese": "チップ、助言", "example": "How much should I tip?"},
        {"english": "sold out", "japanese": "売り切れ", "example": "Sorry, it's sold out."},
        {"english": "on sale", "japanese": "セール中", "example": "These shoes are on sale."},
        {"english": "try on", "japanese": "試着する", "example": "Can I try this on?"},
    ],
    "旅行・移動": [
        {"english": "boarding pass", "japanese": "搭乗券", "example": "Here's my boarding pass."},
        {"english": "luggage", "japanese": "荷物", "example": "I lost my luggage."},
        {"english": "directions", "japanese": "道順", "example": "Can you give me directions?"},
        {"english": "transfer", "japanese": "乗り換え", "example": "You need to transfer at the next station."},
        {"english": "delay", "japanese": "遅延", "example": "The flight has a two-hour delay."},
        {"english": "round trip", "japanese": "往復", "example": "I'd like a round trip ticket."},
        {"english": "get off", "japanese": "降りる", "example": "We get off at the next stop."},
        {"english": "drop off", "japanese": "降ろす、届ける", "example": "Can you drop me off at the station?"},
        {"english": "pick up", "japanese": "迎えに行く、拾う", "example": "I'll pick you up at the airport."},
        {"english": "check in", "japanese": "チェックインする", "example": "What time can we check in?"},
        {"english": "book", "japanese": "予約する", "example": "I booked a hotel online."},
        {"english": "cancel", "japanese": "キャンセルする", "example": "I need to cancel my reservation."},
    ],
    "句動詞（よく使う）": [
        {"english": "bring up", "japanese": "話題に出す、育てる", "example": "Don't bring up that topic."},
        {"english": "call off", "japanese": "中止する", "example": "They called off the event."},
        {"english": "carry on", "japanese": "続ける", "example": "Please carry on with your work."},
        {"english": "check out", "japanese": "調べる、見てみる", "example": "Check out this new app!"},
        {"english": "end up", "japanese": "結局〜になる", "example": "We ended up staying home."},
        {"english": "find out", "japanese": "発見する、知る", "example": "I just found out the truth."},
        {"english": "give up", "japanese": "あきらめる", "example": "Don't give up!"},
        {"english": "go through", "japanese": "経験する、通り抜ける", "example": "She's going through a hard time."},
        {"english": "look into", "japanese": "調査する", "example": "I'll look into the problem."},
        {"english": "make up", "japanese": "作り上げる、仲直りする", "example": "Did you make up that story?"},
        {"english": "run into", "japanese": "偶然出会う", "example": "I ran into an old friend."},
        {"english": "take over", "japanese": "引き継ぐ", "example": "She took over the company."},
        {"english": "work out", "japanese": "うまくいく、運動する", "example": "Everything will work out."},
        {"english": "put up with", "japanese": "我慢する", "example": "I can't put up with this noise."},
        {"english": "look up to", "japanese": "尊敬する", "example": "I really look up to her."},
    ],
    "つなぎ言葉・表現": [
        {"english": "as far as I know", "japanese": "私の知る限り", "example": "As far as I know, the meeting is at 3."},
        {"english": "in case", "japanese": "〜の場合に備えて", "example": "Take an umbrella in case it rains."},
        {"english": "no wonder", "japanese": "どうりで、なるほど", "example": "No wonder you're tired."},
        {"english": "on the other hand", "japanese": "一方で", "example": "On the other hand, it could be fun."},
        {"english": "it depends", "japanese": "場合による", "example": "It depends on the weather."},
        {"english": "for some reason", "japanese": "なぜか", "example": "For some reason, I feel nervous."},
        {"english": "at least", "japanese": "少なくとも", "example": "At least we tried."},
        {"english": "so far", "japanese": "今のところ", "example": "So far, everything is going well."},
        {"english": "right away", "japanese": "すぐに", "example": "I'll do it right away."},
        {"english": "all of a sudden", "japanese": "突然", "example": "All of a sudden, it started raining."},
        {"english": "on purpose", "japanese": "わざと", "example": "I didn't do it on purpose."},
        {"english": "after all", "japanese": "結局、やっぱり", "example": "After all, it wasn't so bad."},
    ],
}
